namespace TouhouPets
{
    public enum TouhouPetID : int
    {
        None = 0,
        Cirno = 1,
        Alice = 2,
        AliceLegacy = 3,
        Aya = 4,
        Chen = 5,
        Daiyousei = 6,
        Doremy = 7,
        Eirin = 8,
        Flandre = 9,
        Hecatia = 10,
        Hina = 11,
        Iku = 12,
        Junko = 13,
        Kaguya = 14,
        Keine = 15,
        Koakuma = 16,
        Kogasa = 17,
        Koishi = 18,
        Kokoro = 19,
        Letty = 20,
        Lily = 21,
        Luna = 22,
        Lunasa = 23,
        Lyrica = 24,
        Marisa = 25,
        Meirin = 26,
        Merlin = 27,
        Minoriko = 28,
        Moku = 29,
        Momoyo = 30,
        Murasa = 31,
        Mystia = 32,
        Nitori = 33,
        Patchouli = 34,
        Piece = 35,
        Raiko = 36,
        Ran = 37,
        Reimu = 38,
        Reisen = 39,
        Remilia = 40,
        Rin = 41,
        Rukoto = 42,
        Rumia = 43,
        Sakuya = 44,
        Sanae = 45,
        Satori = 46,
        Sekibanki = 47,
        Shinki = 48,
        Sizuha = 49,
        Star = 50,
        Suika = 51,
        Sunny = 52,
        Tenshin = 53,
        Tewi = 54,
        Utsuho = 55,
        Wakasagihime = 56,
        Wriggle = 57,
        Youmu = 58,
        Yuka = 59,
        Yukari = 60,
        Yuyuko = 61,
        Count
    }
}
